version: "2"
services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - 90:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  db:
    image: mysql:5.7.22
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD= supersecret
      - MYSQL_DATABASE=SEED
      - MYSQL_USER=SEED
      - MYSQL_PASSWORD=SEED
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  backend1:
    image: systelab/seed-jee:latest
    labels:
      - "traefik.frontend.rule=PathPrefix:/seed/v1/patients"
      - "traefik.frontend.priority=3"
      - "traefik.weight=1"
      - "traefik.port=8080"
      - "traefik.backend.loadbalancer.method=wrr"
    depends_on:
      - db
      - logstash
    environment:
      - MYSQL_URI=db:3306
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=SEED
      - MYSQL_USER=SEED
      - MYSQL_PASSWORD=SEED
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  backend2:
    image: systelab/seed-jee:latest
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.priority=1"
      - "traefik.weight=1"
      - "traefik.port=8080"
      - "traefik.backend.loadbalancer.method=wrr"
    depends_on:
      - db
      - logstash
    environment:
      - MYSQL_URI=db:3306
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=SEED
      - MYSQL_USER=SEED
      - MYSQL_PASSWORD=SEED
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  frontent1:
    image: systelab/seed-angular:latest
    ports:
      - 80:80
    depends_on:
      - traefik
    environment:
      - BACKEND=http://127.0.0.1:90
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
    volumes:
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  logstash:
    image: systelab/logstash-with-multiline-plugin:version-1.0
    volumes:
      - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./docker/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5000:5000
      - 12201:12201/udp
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.1
    volumes:
      - ./docker/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 9090:8080
